In [1]:
import torch
torch.__version__

'2.5.1+cu121'

Question1 Create a random tensor with shape (7, 7).

In [2]:
random_tensor =torch.rand(7,7)


Q2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
random_tensor2 = torch.rand(1, 7)
random_tensor2_transposed = random_tensor2.t()
result = torch.matmul(random_tensor, random_tensor2_transposed)
print(result)

tensor([[1.2529],
        [2.1690],
        [1.6901],
        [1.0751],
        [1.0016],
        [2.0415],
        [1.5601]])


Q3. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [ ]:
torch.manual_seed(0)
random_tensor = torch.rand(7, 7)
random_tensor2 = torch.rand(1, 7)
random_tensor2_transposed = random_tensor2.t()
result = torch.matmul(random_tensor, random_tensor2_transposed)
print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


Q4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [3]:
# Set the manual seed
torch.manual_seed(1234)

# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('Device:', device)
else:
    device = torch.device('cpu')
    print('CUDA not available, using CPU instead.')

# here, im creating two random tensors of shape (2, 3)
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

# i am now Printing the tensors
print(tensor1, tensor2)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


Q5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [8]:
# i am setting the manual seed below
torch.manual_seed(1234)

# i am checking if CUDA is available with the below codes
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('Device:', device)
else:
    device = torch.device('cpu')
    print('CUDA not available, using CPU instead.')

# i am creating two random tensors of shape (2, 3) on the device
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

# Transposing the second tensor to shape (3, 2)
tensor2_transposed = tensor2.t()

# Performing matrix multiplication
result = torch.matmul(tensor1, tensor2_transposed)

# Printing the result and its shape
print(result, result.shape)

Device: cuda
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


Q6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [7]:
max_value = torch.max(result)
min_value = torch.min(result)

# Print the maximum and minimum values
print("Maximum value:", max_value.item())
print("Minimum value:", min_value.item())

Maximum value: 0.7667766809463501
Minimum value: 0.27863210439682007


Q7. Find the maximum and minimum index values of the output of question 6 above.

In [9]:
# Find the indices of the maximum and minimum values
max_index = torch.argmax(result)
min_index = torch.argmin(result)

# Print the indices
print("Index of maximum value:", max_index.item())
print("Index of minimum value:", min_index.item())

Index of maximum value: 1
Index of minimum value: 0


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [10]:
# Set the random seed
torch.manual_seed(7)
# Create a random tensor with shape (1, 1, 1, 10)
tensor1 = torch.rand(1, 1, 1, 10)

# Remove dimensions of size 1
tensor2 = torch.squeeze(tensor1)

# Print the tensors and their shapes
print("First tensor:", tensor1)
print("Shape of first tensor:", tensor1.shape)
print("Second tensor:", tensor2)
print("Shape of second tensor:", tensor2.shape)

First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of first tensor: torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of second tensor: torch.Size([10])
